all:
  hosts:
  children:
    k8s_masters:
      hosts:
        master_node01:
          ansible_ssh_user: jonathan
          ansible_ssh_pass: Superbon2022
          ansible_sudo_pass: Superbon2022
    k8s_nodes:
      hosts:
        worker_node01:
          ansible_ssh_user: jonathan
          ansible_ssh_pass: Superbon2022
          ansible_sudo_pass: Superbon2022
        worker_node02:
          ansible_ssh_user: jonathan
          ansible_ssh_pass: Superbon2022
          ansible_sudo_pass: Superbon2022
    ansbile_controllers:
      hosts:
        ansbile:
          ansible_ssh_user: jonathan
          ansible_ssh_pass: Superbon2022
          ansible_sudo_pass: Superbon2022
