all:
  hosts:
  children:
    k8s_masters:
      hosts:
        master_node01:
          ansible_host: 192.168.18.150
    k8s_nodes:
      hosts:
        worker_node01:
          ansible_host: 192.168.18.151
        worker_node02:
          ansible_host: 192.168.18.152
