all:
  hosts:
  children:
    k8s_masters:
      hosts:
        master_node01:
          ansible_ssh_user: jonathan
          ansible_ssh_pass: Superbon202@
          ansible_sudo_pass: Superbon202@
    k8s_nodes:
      hosts:
        worker_node01:
          ansible_ssh_user: jonathan
          ansible_ssh_pass: Superbon202@
          ansible_sudo_pass: Superbon202@
        worker_node02:
          ansible_ssh_user: jonathan
          ansible_ssh_pass: Superbon202@
          ansible_sudo_pass: Superbon202@
