- hosts: master_node01

  tasks:
    - name: Cleaning all old resources.
      shell: |
        kubectl delete clusterrole jenkins-admin
        kubectl delete serviceaccount jenkins-admin -n devops-tools
        kubectl delete clusterrolebinding jenkins-admin -n devops-tools
        kubectl delete storageclass local-storage 
        kubectl delete pv jenkins-pv-volume
        kubectl delete pvc jenkins-pv-claim -n devops-tools
        kubectl delete deployment jenkins -n devops-tools
        kubectl delete jenkins-service -n devops-tools
        kubectl delete namespace devops-tools
      ignore_errors: true

    - name: Creating devops-tools namespace
      ansible.builtin.shell: kubectl create namespace devops-tools

    - name: Creating ClusterRole
      ansible.builtin.shell: kubectl create clusterrole jenkins-admin --verb='*' --resource='*'

    - name: Creating ServiceAccount
      ansible.builtin.shell: kubectl create serviceaccount jenkins-admin -n devops-tools

    - name: Creating ClusterRoleBinding
      ansible.builtin.shell: kubectl create clusterrolebinding jenkins-admin --clusterrole=jenkins-admin --serviceaccount=devops-tools:jenkins-admin

    - name: Creating Volume
      ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/jonny-levi/k8s/main/jenkins/volume.yaml

    - name: Creating Deployment
      ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/jonny-levi/k8s/main/jenkins/deployment.yaml

    - name: Creating service for jenkins
      ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/jonny-levi/k8s/main/jenkins/service.yaml

    - name: Update repositories cache and install "foo" package
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Update repositories cache and install "foo" package
      ansible.builtin.apt:
        name: openjdk-11-jre
