- hosts: master_node01

  tasks:
    - name: Cloning repository localy
      ansible.builtin.shell: git clone https://github.com/scriptcamp/kubernetes-jenkins
    
    - name: Creating devops-tools namespace
      ansible.builtin.shell: kubectl create namespace devops-tools
    
    - name: Creating ClusterRole
      ansible.builtin.shell: kubectl create clusterrole jenkins-admin --verb='*' --resource='*' 

    - name: Creating ServiceAccount
      ansible.builtin.shell: kubectl create serviceaccount jenkins-admin -n devops-tools

    - name: Creating ClusterRoleBinding
      ansible.builtin.shell: kubectl create clusterrolebinding jenkins-admin --clusterrole=jenkins-admin --serviceaccount=devops-tools:jenkins-admin
    
    - name: Creating volume on the node for jenkins
      ansible.builtin.blockinfile:
        path: /tmp/jenkins/volume.yaml
        create: true
        block: |
          kind: StorageClass
          apiVersion: storage.k8s.io/v1
          metadata:
            name: local-storage
          provisioner: kubernetes.io/no-provisioner
          volumeBindingMode: WaitForFirstConsumer
          ---
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: jenkins-pv-volume
            labels:
              type: local
          spec:
            storageClassName: local-storage
            claimRef:
              name: jenkins-pv-claim
              namespace: devops-tools
            capacity:
              storage: 10Gi
            accessModes:
              - ReadWriteOnce
            local:
              path: /mnt
            nodeAffinity:
              required:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - worker-node01
          ---
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: jenkins-pv-claim
            namespace: devops-tools
          spec:
            storageClassName: local-storage
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 3Gi
    
    - name: Creating ClusterRoleBinding
      ansible.builtin.shell: kubectl create -f /tmp/jenkins/volume.yaml
    
    - name: Creating volume on the node for jenkins
      ansible.builtin.blockinfile:
        path: /tmp/jenkins/deployment-jenkins.yaml
        create: true
        block: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: jenkins
            namespace: devops-tools
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: jenkins-server
            template:
              metadata:
                labels:
                  app: jenkins-server
              spec:
                securityContext:
                      fsGroup: 1000
                      runAsUser: 1000
                serviceAccountName: jenkins-admin
                containers:
                  - name: jenkins
                    image: jenkins/jenkins:lts
                    resources:
                      limits:
                        memory: "2Gi"
                        cpu: "1000m"
                      requests:
                        memory: "500Mi"
                        cpu: "500m"
                    ports:
                      - name: httpport
                        containerPort: 8080
                      - name: jnlpport
                        containerPort: 50000
                    livenessProbe:
                      httpGet:
                        path: "/login"
                        port: 8080
                      initialDelaySeconds: 90
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 5
                    readinessProbe:
                      httpGet:
                        path: "/login"
                        port: 8080
                      initialDelaySeconds: 60
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                    volumeMounts:
                      - name: jenkins-data
                        mountPath: /var/jenkins_home
                volumes:
                  - name: jenkins-data
                    persistentVolumeClaim:
                        claimName: jenkins-pv-claim
                      
    - name: Creating ClusterRoleBinding
      ansible.builtin.shell: kubectl create -f /tmp/jenkins/deployment-jenkins.yaml

    - name: Creating volume on the node for jenkins
      ansible.builtin.blockinfile:
        path: /tmp/jenkins/service-jenkins.yaml
        create: true
        block: |
          apiVersion: v1
          kind: Service
          metadata:
            name: jenkins-service
            namespace: devops-tools
            annotations:
                prometheus.io/scrape: 'true'
                prometheus.io/path:   /
                prometheus.io/port:   '8080'
          spec:
            selector:
              app: jenkins-server
            type: NodePort
            ports:
              - port: 8080
                targetPort: 8080
                nodePort: 32000

    - name: Creating ClusterRoleBinding
      ansible.builtin.shell: kubectl create -f /tmp/jenkins/service-jenkins.yaml

    
    


