- hosts: all 
  become: true
  tasks:
    
    #- name: test
    #ansible.builtin.shell: |
    #mkdir -p /home/jonathan/.kube
    #sudo cp -i /etc/kubernetes/admin.conf /home/jonathan/.kube/config
    #sudo chown jonathan:jonathan /home/jonathan/.kube/config
    #delegate_to: master_node01
    #become: true
    #become_user: root

    - name: Run a command as the apache user
      command: cp -i /etc/kubernetes/admin.conf /home/jonathan/.kube/config
      become_user: jonathan
      delegate_to: master_node01
