- hosts: all
  become: true
  tasks:

  - name: Copy file with owner and permissions
    ansible.builtin.copy: 
      src: /etc/kubernetes/admin.conf
      dest: /home/jonathan/.kube/config
      owner: jonathan
      group: jonathan
      mode: '0755'
      remote_src: yes
    delegate_to: master_node01
    become: true

    #- name: Initializing Kubernetes Cluster - copy config
    #ansible.builtin.shell:
    #sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    #delegate_to: master_node01


    #- name: Initializing Kubernetes Cluster - change permissions
    #ansible.builtin.shell:
    #sudo chown $(id -u):$(id -g) $HOME/.kube/config
    #delegate_to: master_node01


  - name: Initializing Kubernetes Cluster
    ansible.builtin.shell:
      kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
    become_user: jonathan
    delegate_to: master_node01

  - name: Copy join command to local file
    local_action: copy content={{ init_output.stdout_lines[-2:] }} dest="./join-command"
    delegate_to: master_node01

