---
- hosts: k8s_masters
  gather_facts: true
  become: true
  pre_tasks:
    - name: variables
      ansible.builtin.include_vars: vars/all.yml
  roles:
    - { role: k8s/k8s_masters }

- hosts: k8s_nodes
  gather_facts: true
  become: true
  pre_tasks:
    - name: variables
      ansible.builtin.include_vars: vars/all.yml
  roles:
    - { role: k8s/k8s_nodes }
