- name: Check if namespace exists
  ansible.builtin.shell: |
    kubectl get namespace argocd --no-headers || echo "NotFound"
  register: namespace_check
  failed_when: namespace_check.rc not in [0, 1] # Ignore errors if namespace doesn't exist

- name: Create namespace if it does not exist
  ansible.builtin.shell: |
    kubectl create namespace argocd
  when: "'NotFound' in namespace_check.stdout"
