---
- name: Check if namespace exists
  ansible.builtin.shell: |
    kubectl get namespace monitoring --no-headers || echo "NotFound"
  register: namespace_check
  failed_when: namespace_check.rc not in [0, 1] # Ignore errors if namespace doesn't exist
  become_user: jonathan

- name: Create namespace if it does not exist
  ansible.builtin.shell: |
    kubectl create namespace monitoring
  when: "'NotFound' in namespace_check.stdout"
  become_user: jonathan

- name: Add Grafana chart repo
  kubernetes.core.helm_repository:
    name: grafana 
    repo_url: "https://grafana.github.io/helm-charts"
    update_repo_cache: true

- name: Deploy latest version of Grafana chart inside monitoring namespace 
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana/grafana
    release_namespace: monitoring

