- name: Verifying cluster is up and functioning
  ansible.builtin.shell: kubectl get nodes
  register: cluster_results
  retries: 10
  until: cluster_results.rc == 0

- name: Copy a directory containing configuration to remote host
  ansible.builtin.copy:
    src: ~/k8s/roles/k8s/k8s_masters/vsphere-csi
    dest: ~/

- name: prerequisites - preparing infrastracture - vSphere-CSI storage driver
  ansible.builtin.shell: kubectl apply -f ~/vsphere-csi/storageClass.yml

- name: prerequisites - preparing infrastracture - vSphere-CSI storage controller
  ansible.builtin.shell: kubectl apply -f ~/vsphere-csi/vsphere-cloud-controller-manager.yaml

- name: prerequisites - preparing infrastracture - vSphere-CSI storage controller - creating namespace
  ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.7.0/manifests/vanilla/namespace.yaml

- name: Initializing vSphere-CSI storage controller
  ansible.builtin.blockinfile:
    path: ~/vsphere-csi/csi-vsphere.conf
    block: |
      [Global]
      cluster-id = "<cluster-id>"
      cluster-distribution = "<cluster-distribution>"
      ca-file = <ca file path> # optional, use with insecure-flag set to false
      thumbprint = "<cert thumbprint>" # optional, use with insecure-flag set to false without providing ca-file

      [VirtualCenter "<IP or FQDN>"]
      insecure-flag = "<true or false>"
      user = "<username>"
      password = "<password>"
      port = "443"
    create: true

- name: Initializing vSphere-CSI storage controller
  ansible.builtin.shell: kubectl create secret generic vsphere-config-secret --from-file=~/vsphere-csi/csi-vsphere.conf --namespace=vmware-system-csi

- name: Initializing vSphere-CSI storage controller
  ansible.builtin.shell: $ kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/v2.7.0/manifests/vanilla/vsphere-csi-driver.yaml
