- name: Join nodes to cluster
  ansible.builtin.shell: "kubeadm join {{ hostvars[item]['ansible_default_ipv4']['address'] }}:6443 --token {{ join_token }} --discovery-token-unsafe-skip-ca-verification --cri-socket {{ container_runtime }}"
  with_items: "{{ groups.k8s_masters }}"
