- name: Join nodes to cluster
  ansible.builtin.shell: "kubeadm join {{ master_node01 }}:6443 --token {{ join_token }} --discovery-token-unsafe-skip-ca-verification --cri-socket {{ container_runtime }}"
