apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: guess-my-number
  name: guess-my-number-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31111
  selector:
    app: guess-my-number
  type: NodePort
status:
  loadBalancer: {}
