apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: guess-my-number
  name: guess-my-number
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guess-my-number
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: guess-my-number
    spec:
      containers:
      - image: jonathanlevi/guess_my_number:0.0.5
        name: guess-my-number
        ports:
          - containerPort: 8080
        resources: {}
status: {}
