- name: Initialize the Kubernetes cluster using kubeadm
  ansible.builtin.shell: "sudo kubeadm init --token {{ join_token }} --pod-network-cidr=10.244.0.0/16 --cri-socket {{ container_runtime }}"
  register: init_output

- debug:
    var: init_output.stdout_lines

- name: Creating .kube directory
  ansible.builtin.shell: mkdir -p /home/"{{hostvars['master_node01']['ansible_ssh_user']}}"/.kube
  become_user: "{{hostvars['master_node01']['ansible_ssh_user']}}"

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{hostvars['master_node01']['ansible_ssh_user']}}/.kube/config
    owner: "{{hostvars['master_node01']['ansible_ssh_user']}}"
    group: "{{hostvars['master_node01']['ansible_ssh_user']}}"
    mode: "0755"
    remote_src: yes
  become: true

- name: Verifying if directory is created
  ansible.builtin.debug:
    msg: cd /home/"{{hostvars['master_node01']['ansible_ssh_user']}}"/

- name: Initializing Kubernetes Cluster
  ansible.builtin.shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
  become_user: "{{hostvars['master_node01']['ansible_ssh_user']}}"
