apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
  - templates/namespace.yaml
  - templates/minio-pvc.yaml
  - templates/minio-deployment.yaml
  - templates/minio-service.yaml
