apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pig-game
  name: pig-game-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31112
  selector:
    app: pig-game
  type: NodePort
status:
  loadBalancer: {}
