apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pig-game
  name: pig-game-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31112
  selector:
    app: pig-game-number
  type: NodePort
status:
  loadBalancer: {}
