apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-minio-data
  namespace: velero
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client-2
  resources:
    requests:
      storage: 500Gi
